baseURL: https://linux.ime.usp.br/~ygortavela/mac0499/
title: Trabalho de Formatura Supervisionado
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Trabalho de Formatura Supervisionado
  description: "Neste blog serão reunidos informações relacionadas ao trabalho de pesquisa"
  keywords: [Blog, Portfolio, PaperMod]
  author: ["Ygor Tavela", "Washington Luiz Meireles"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    iconHeight: 35

  homeInfoParams:
    Title: "Trabalho de Formatura Supervisionado"
    Content: |
      # Explorando Padrões de Comunicação para Servir Sistemas Inteligentes
      &nbsp;

      Washington Luiz Meireles de Lima (luiz.meireles@usp.br)

      Ygor Tavela Alves (ygor_tavela@usp.br)

      &nbsp;

      ### Orientadores: 

      &nbsp;

      Prof. Dr. Alfredo Goldman

      Ms. Renato Cordeiro Ferreira

      &nbsp;

      ### Resumo: 

      &nbsp;

      Sistemas Inteligentes fazem a ponte entre usuários e o Aprendizado de Máquina (ML) para atingir objetivos significativos. Em particular, a inteligência do ML evolui e melhora com o tempo, analisando como os usuários interagem com o sistema. Tais sistemas possuem três eixos de mudança: código, dados e modelo. Isso amplia a complexidade de desenvolvimento se comparado a sistemas tradicionais, o que traz  à tona novos desafios. Dentre eles, está a escalabilidade, que engloba as etapas de coleta de dados, engenharia de características (_features_), reinamento do modelo de ML, e o serviço do modelo de ML em produção. Nessa última etapa, uma decisão arquitetural importante é a escolha do padrão de comunicação utilizado para servir o modelo, que pode ser classificado de acordo com o tipo de responsividade: síncrono ou assíncrono. No contexto de sistemas inteligentes, a escolha de um padrão de comunicação pode não se basear apenas em premissas já conhecidas do desenvolvimento de sistemas tradicionais. Por isso, o objetivo desta pesquisa é de explorar _trade-offs_ de diferentes padrões, em particular, a API RPC (síncrona) e a Mensageria (assíncrona).

  socialIcons:

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: proposal
      name: proposta
      url: /proposta.pdf
      weight: 10
    - identifier: monography
      name: monografia
      url: /monografia.pdf
      weight: 20
    - identifier: poster
      name: poster
      url: /poster.pdf
      weight: 30
    - identifier: subjective
      name: considerações pessoais
      url: /subjective.pdf
      weight: 40
    - identifier: presentation
      name: apresentação
      url: https://docs.google.com/presentation/d/15TytmSxHKKd84-LWGIclpwmqTwTjWJcJv8mEqP07fug/edit?usp=sharing
      weight: 50
    - identifier: repository
      name: repositório
      url: https://github.com/washington-ygor-tcc
      weight: 60